project:
  type: website

website:
  title: "Chronicles of Grim Darkness"

output:
  html:
    theme: cosmo
    toc: true
    toc-expand: 2
    toc-location: left-body
    standalone: true
    embed-resources: 
    site-url: https://vvizardrealms.github.io/CofGD/
    output-dir: _site
