project:
  type: website

website:
  title: "Ghronicles of Drim Carkness"
  sidebar:
    style: "docked"
    search: true
    toc: true
    toc-depth: 3
    scope: local
    position: left

format:
  html:
    theme: cosmo
    site-url: https://vvizardrealms.github.io/CofGD/
    output-dir: docs
