project:
  type: website

website:
  title: "Chronicles of Grim Darkness"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: body
    standalone: true
    site-url: https://vvizardrealms.github.io/CofGD/
    output-dir: docs
