# HUMAN CHARACTERS

To create a Human character, pick a Home World, A Career Path, and a
Role. Starting size is 5.

## Home Worlds

### HOME WORLD: Feral World

#### Free Talents:

The Old Ways \[Primitive and Improvised Weapons do additional +1
damage\]

#### Discounted Characteristics:

Strength

Toughness

### HOME WORLD: Forge World

#### Free Talents:

Omnissiah's Chosen \[Automatic success when performing trivial repairs\]

#### Discounted Characteristics:

Intelligence

Toughness

### HOME WORLD: Highborn

#### Free Talents:

Breeding Counts \[Once per session may leverage background to gain
significant social advantage (call in a favour, access restricted areas,
gaining preferential treatment etc)\]

#### Discounted Characteristics:

Fellowship

Composure

### HOME WORLD: Hive World

#### Free Talents:

Teeming Masses \[Movement is never impeded by crowds. Additional +2 to
rolls for navigating or moving through enclosed or crowded spaces\]

#### Discounted Characteristics:

Agility

Perception

### HOME WORLD: Shrine World

#### Free Talents:

Faith in the Creed \[Whenever you spend a Fate point, roll 1d10. On a 1
that Fate point is immediately restored\]

#### Discounted Characteristics:

Fellowship

Willpower

### HOME WORLD: Voidborn

#### Free Talents:

Child of the Dark \[May re-roll Willpower tests. Additionally, gain +3
to dice pool to rolls for moving in zero-g\]

#### Discounted Characteristics:

Intelligence

Willpower

### HOME WORLD: Agri-World

#### Free Talents:

Strength from the Land \[May re-roll Strength tests\]

#### Discounted Characteristics:

Strength

Fellowship

### HOME WORLD: Feudal

#### Free Talents:

At Home in Armour \[Ignores defence penalties from wearing armour\]

#### Discounted Characteristics:

Perception

Agility

### HOME WORLD: Frontier

#### Free Talents:

Rely on None but Yourself \[Gain a +2 to dice pool for Tech-Use tests
involving weapons, and a +1 to dice pool when repairing damaged items\]

#### Discounted Characteristics:

Perception

Composure

## Career Paths

### CAREER PATH: Adept

#### Free Specialties/Talents:

Common Lore (Adeptus Administratum)

Scholastic Lore (any)

Language (High Gothic) \[Knows the High Gothic language\]

Master of Paperwork \[Can procure rare items as though they were
common\]

#### Discounted Skills:

Commerce

Medicae

Scholastic Lore

Common Lore

#### Starting Equipment:

Laspistol or stub automatic, Imperial robes, autoquil, chrono,
dataslate, medi-kit

### CAREER PATH: Arbitrator

#### Free Specialties/Talents:

Common Lore (Adeptus Arbites)

Common Lore (Underworld)

Face of the Law \[Can re-roll any Intimidate or Inquiry test, or can
substitute max Fate for number of successes\]

#### Discounted Skills:

Awareness

Investigation

Inquiry

Intimidate

#### Starting Equipment:

Shotgun or shock maul, carapace armour, 3 doses of stimm, manacles, 12
lho sticks

### CAREER PATH: Cleric

#### Free Specialties/Talents:

Common Lore (Adeptus Ministorum)

Common Lore (Imperial Creed)

Language (High Gothic)

Faith is All \[When spending a fate point to gain +3 to a dice pool,
gain +5 instead\]

#### Discounted Skills:

Investigate

Charm

Command

Inquiry

#### Starting Equipment:

Handflamer or Warhammer and stub revolver, Imperial robes or flak vest,
backpack, glow-globe, monotask servo skull (Loud hailer)

### CAREER PATH: Guardsman

#### Free Specialties/Talents:

Common Lore (Imperial Guard)

Pilot (Surface)

Survival (Navigation)

Medicae (Combat First Aid)

Hammer of the Emperor \[Can re-roll any 1s or 2s on attack rolls)

#### Discounted Skills:

Athletics

Command

Ballistic Skill

Weapon Skill

#### Starting Equipment:

Lasgun (or laspistol and sword), combat vest, Imperial Guard flak
armour, grapnel and line, 12 lho sticks, magnoculars

### CAREER PATH: Imperial Psyker

#### Free Specialties/Talents:

Common Lore (Adeptus Astra Telepathica)

Forbidden Lore (The Warp)

Psyniscience \[Can detect Psychic activity\]

Psyker \[Can manifest Psychic Powers\]

Constant Threat \[Can alter result of Psychic Phenomenon by amount equal
to max Fate\]

#### Discounted Skills:

Awareness

Deceive

Inquiry

Investigation

#### Starting Equipment:

Laspistol, staff or whip, light flak cloak or flak vest, microbead, psy
focus

### CAREER PATH: Outcast

#### Free Specialties/Talents:

Common Lore (Underworld)

Security (Sleight of Hand)

Acrobatics (Dodge)

Never Quit \[Can spend a fate point to ignore all effects of damage,
including unconsciousness, for a number of turns equal to their
toughness\]

#### Discounted Skills:

Acrobatics

Stealth

Charm

Deceive

#### Starting Equipment:

Autopistol or laspistol, chainsword, armoured bodyglove or flak vest,
injector, 2 doses of obsurca or slaught

### CAREER PATH: Rogue Trader

#### Free Specialties/Talents:

Common Lore (Rogue Traders)

Pilot (any)

Language (any alien language)

Inured to the Xenos \[+1 to dice pool to any Fear tests caused by
aliens, +2 to any Interactions with alien characters\]

#### Discounted Skills:

Charm

Commerce

Investigation

Command

#### Starting Equipment:

Laspistol or autopistol, shock maul, mesh cloak or carapace armour,
auspex, chrono

### CAREER PATH: Sister of Battle

#### Free Specialties/Talents:

Common Lore (Adepta Sororitas)

Scholastic Lore (Tactica Imperialis)

Language (High Gothic)

Incorruptible Devotion \[This character cannot gain Corruption, they
gain Insanity instead\]

#### Discounted Skills:

Athletics

Charm

Intimidate

Medicae

#### Starting Equipment:

Hand flamer or laspistol, chainblade, armoured bodyglove, chrono,
dataslate, stab-light, micro-bead

### CAREER PATH: Tech-Priest

#### Free Specialties/Talents:

Common Lore (Adeptus Mechanicus)

Tech-Use (any)

Language (Techna-Lingua) \[Can speak the machine language\]

Mechadendrite use \[\]

Mechanicus Implants \[\]

#### Discounted Skills:

Awareness

Security

Tech-Use

Trade

#### Starting Equipment:

Autogun or hand cannon, monotask servo-skull (utility) or optical
mechadendrite, Imperial robes, 2 vials of sacred unguents.

## Roles

### ROLE: Assassin

#### Free Talents:

Jaded \[Impervious to mundane horrors\]

Sure Kill \[Spend a Fate point after a successful attack to deal double
damage\]

### ROLE: Chirurgeon

#### Free Talents:

Takedown \[May opt to deal no damage in a melee attack and instead knock
a target prone and stunned\]

Dedicated Healer \[Spend a Fate point and automatically succeed a
Medicae roll\]

### ROLE: Desperado

#### Free Talents:

Quick Draw \[Can immediately draw a weapon and use it\]

Move and Shoot \[May spend a Fate point to perform an attack in addition
to whichever action was taken that round\]

### ROLE: Hierophant

#### Free Talents:

Double Team \[If an ally is engaged in melee combat with the same enemy,
this character gains +1 to their dice pool for melee attacks. If more
than one ally is engaged, gain +2.\]

Sway the Masses \[May spend a Fate point and automatically succeed a
Charm, Command, or Intimidate test\]

### ROLE: Sage

#### Free Talents:

Clues from the Crowds \[Once per session may re-roll tests to gather
information from other people\]

Quest for Knowledge \[Spend a Fate point and automatically succeed a
Lore or Intelligence test\]

### ROLE: Seeker

#### Free Talents:

Keen Intuition \[May re-roll failed Awareness rolls, taking a --1 to the
dice pool on the re-roll\]

Nothing Escapes My Sight \[May spend a Fate point and automatically pass
an Awareness or Inquiry roll\]

### ROLE: Warrior

#### Free Talents:

Rapid Reload \[May reload as a free action\]

Expert at Violence \[May spend a Fate point to double Weapon Skill or
Ballistic Skill for a single test\]

# ASTARTES CHARACTERS

Astartes characters gain all the Space Marine Implant talents. They then
choose a Chapter, then a Career Path. Starting size is 6.

#### Starting Talents:

Unnatural Strength \[Rolls using Strength pass on 6+ rather than 8+\]

Unnatural Toughness \[Rolls using Toughness pass on 6+ rather than 8+\]

Larraman's Organ \[Halve any lethal damage taken, rounded up\]

Catalepsean Node \[No penalties from lack of sleep\]

Preomnor \[+2 to dice pools for tests resisting ingested poison\]

Omophagea \[By devouring a portion of an enemy a Space Marine may gain
access to certain information or skills that enemy possessed, up to the
GM's discretion. This information or skill is retained for a number of
hours equal to the dots in Space Marine's Intelligence\]

Multi-lung \[May re-roll failed tests to resist drowning, asphyxiation,
or gases\]

Heightened Senses \[All five senses are superhuman\]

Sus-an Membrane \[May enter suspended animation by meditation.
Automatically activates once lethal damage is maxed\]

Melanchromic Organ \[+1 to dice pools for tests resisting radiation\]

Oolitic Kidney \[May re-roll failed tests to resist poison or toxin\]

Neuroglottis \[May detect poison or toxins using an Awareness check.
Also may track an opponent he has tasted with a Survival test\]

Mucranoid \[May re-roll failed tests to resist extreme temperatures\]

Betcher's Gland \[Can spit acid\]

Progenoids \[Gene seeds required for creating more Astartes. Willpower
test is required to leave the Progenoids of a fallen brother behind.\]

Black Carapace \[May use Power Armour without penalty\]

#### Starting Equipment:

Astartes power armour, Astartes bolt pistol, 3 Astartes frag grenades, 3
Astartes krak grenades, Astartes combat knife, repair cement.

## CHAPTERS

### CHAPTER: Blood Angels

Blood Frenzy \[Once per combat may enter a frenzy for number of rounds
equal to Willpower. During frenzy may re-roll failed Weapon Skill rolls,
and melee attacks gain the 9-Again rule\]

### CHAPTER: Dark Angels

Stoic Defence \[Once per combat may gain 6 Temporary Wounds and half his
speed in order to hold ground or position. Temporary wounds are
immediately removed when affected by any type of damage, and must be
dealt damage to first before normal wounds. These Temporary Wounds are
lost if the position is abandoned either by choice or involuntarily\]

### CHAPTER: Imperial Fists

Siege Master \[Armour of any cover an opponent uses is halved. Armour of
any cover an Imperial Fist uses is doubled.\]

### CHAPTER: Iron Hands

Suffer No Weakness \[Once per combat may select one opponent. For the
duration of that combat, gain a bonus to damage dealt against that enemy
equal to dots in Intelligence\]

### CHAPTER: Raven Guard

Master of the Shadows \[May re-roll failed Stealth tests\]

### CHAPTER: Salamanders

Fire-Born \[Immune to being set on fire. May re-roll failed Trade
tests\]

### CHAPTER: Space Wolves

Wolf Senses \[May re-roll failed perception tests when unhelmeted.
Additionally can see in the dark\]

### CHAPTER: Ultramarines

Favoured Son \[May re-roll any fellowship tests when dealing with
Imperials.\]

### CHAPTER: White Scars

As Swift as the Wind \[May make an Athletics (on foot) or Pilot (in
vehicle) test in order to move as a free action\]

## CAREER PATHS

### CAREER PATH: Apothecary

#### Free Specialties/Talents:

Scholastic Lore (Chymistry)

Forbidden Lore (Mutants)

Tech-Use (Chems)

Enhanced Healing \[Succesful Medicae tests heals double\]

#### Discounted Skills:

Investigation

Scholastic Lore

Medicae

Inquiry

#### Starting Equipment:

Astartes bolter with fire selector, reductor, narthecium

### CAREER PATH: Assault Marine

#### Free Specialties/Talents:

Pilot (Jump Pack)

Weapon Skill (Jump Pack Assaults)

Ballistic Skill (Pistols)

Swift Attack \[May perform two melee attacks in one turn\]

#### Discounted Skills:

Acrobatics

Athletics

Pilot

Weapon Skill

#### Starting Equipment:

Astartes chainsword, Astartes jump pack

### CAREER PATH: Devastator Marine

#### Free Specialties/Talents:

Ballistic Skill (Heavy)

Awareness (Targeting)

Tech-Use (Military Gear)

Immovable Warrior \[When wielding a Heavy weapon behind cover gain +2 to
dice pool on shooting tests, and +3 to rolls resisting a tackle, push,
or knockdown\]

#### Discounted Skills:

Awareness

Tech-Use

Ballistic Skill

Intimidate

#### Starting Equipment:

Astartes heavy bolter with backpack ammo supply

### CAREER PATH: Librarian

#### Free Specialties/Talents:

Forbidden Lore (The Warp)

Scholastic Lore (any)

Psyniscience \[Can detect Psychic activity\]

Battle-Psyker \[Can manifest Psychic Powers\]

#### Discounted Skills:

Common Lore

Forbidden Lore

Investigation

Scholastic Lore

#### Starting Equipment:

Astartes bolter with fire selector, force weapon

### CAREER PATH: Tactical Marine

#### Free Specialties/Talents:

Command (Squad)

Ballistic Skill (Bolter)

Common Lore (Combat Formations)

Bolter Drill \[May take a Command Roll to give himself and all members
of his squad a +1 dice pool buff for their next shooting attack\]

#### Discounted Skills:

Command

Athletics

Ballistic Skill

Weapon Skill

#### Starting Equipment:

Astartes bolter with fire selector, one clip of special issue ammunition

### CAREER PATH: Techmarine

#### Free Specialties/Talents:

Forbidden Lore (Adeptus Mechanicus)

Tech-Use (any)

Language (Techna Lingua) \[Can speak the machine tongue\]

Blessed by the Omnissiah \[Begin the game with Mechadendrite (Servo-Arm)
and Electro-Graft implants\]

#### Discounted Skills:

Forbidden Lore

Tech-Use

Trade

Security

#### Starting Equipment:

Astartes bolter with fire selector, Astartes servo-arm, one common
Cybernetic

### CAREER PATH: Chaplain

#### Free Specialties/Talents:

Forbidden Lore (Traitor Legions)

Inquiry (Interrogation)

Scholastic Lore (Legends)

Fearsome Presence \[May re-roll Intimidate rolls. Additionally, the
squad, if nearby, automatically pass rolls to resist being Intimidated
by a foe\]

#### Discounted Skills:

Command

Intimidate

Inquiry

Scholastic Lore

#### Starting Equipment:

Crozius Arcanum, Skull Helm, Rosarius

# HERETIC CHARACTERS

Heretic characters, although they are either Human or Astartes, have
forsaken their previous lives and instead have embraced the Dark Gods.
Pick a Human or Astartes, then choose alignment. Heretics do not benefit
from Home World, Role, or Chapter bonuses like their loyalist
counterparts. Instead they benefit from bonuses unique to Heretics,
detailed after the Human and Astartes Career Paths.

## HERETIC ASTARTES

Heretic Astartes gain all the Space Marine implant bonuses, then pick a
career path.

#### Starting Talents:

Unnatural Strength \[Rolls using Strength pass on 6+ rather than 8+\]

Unnatural Toughness \[Rolls using Toughness pass on 6+ rather than 8+\]

Larraman's Organ \[Halve any lethal damage taken, rounded up\]

Catalepsean Node \[No penalties from lack of sleep\]

Preomnor \[+2 to dice pools for tests resisting ingested poison\]

Omophagea \[By devouring a portion of an enemy a Space Marine may gain
access to certain information or skills that enemy possessed, up to the
GM's discretion. This information or skill is retained for a number of
hours equal to the dots in Space Marine's Intelligence\]

Multi-lung \[May re-roll failed tests to resist drowning, asphyxiation,
or gases\]

Heightened Senses \[All five senses are superhuman\]

Sus-an Membrane \[May enter suspended animation by meditation.
Automatically activates once lethal damage is maxed\]

Melanchromic Organ \[+1 to dice pools for tests resisting radiation\]

Oolitic Kidney \[May re-roll failed tests to resist poison or toxin\]

Neuroglottis \[May detect poison or toxins using an Awareness check.
Also may track an opponent he has tasted with a Survival test\]

Mucranoid \[May re-roll failed tests to resist extreme temperatures\]

Betcher's Gland \[Can spit acid\]

Progenoids \[Gene seeds required for creating more Astartes. Willpower
test is required to leave the Progenoids of a fallen brother behind.\]

Black Carapace \[May use Power Armour without penalty\]

### CAREER PATH: Champion

#### Free Specialties/Talents:

Forbidden Lore (Traitor Legions)

Forbidden Lore (The Warp)

Scholastic Lore (any)

Inspiring Presence \[May allow allies within sight to use the Champion's
Corruption and Infamy scores and Alignment when spending Infamy\]

#### Discounted Skills:

Command

Intimidate

Charm

Deceive

### CAREER PATH: Chosen

#### Free Specialties/Talents:

Ballistic Skill (any)

Weapon Skill (any)

Intimidate (Violence)

Cold Killer \[When an attack roll results in five or more successes,
double the damage dealt\]

#### Discounted Skills:

Stealth

Intimidate

Ballistic Skill

Weapon Skill

### CAREER PATH: Forsaken

#### Free Specialties/Talents:

Common Lore (any)

Survival (Looting)

Commerce (Bargaining)

Resourceful \[May re-roll failed Survival or Commerce rolls\]

#### Discounted Skills:

Acrobatics

Survival

Commerce

Security

### CAREER PATH: Sorcerer

#### Free Specialties/Talents:

Scholastic Lore (Occult)

Forbidden Lore (Daemons)

Psyniscience \[Can detect Psychic activity\]

Sorcerer \[Can manifest Psychic Powers\]

#### Discounted Skills:

Stealth

Intimidate

Ballistic Skill

Weapon Skill

## HERETIC HUMANS

### CAREER PATH: Apostate

#### Free Specialties/Talents:

Scholastic Lore (any three)

Forbidden Lore (any three)

Serpent\'s Tongue \[Once per session make a Charm or Deceive test to
gain the Peer talent with any organisation of their choice for the
remainder of the session\]

#### Discounted Characteristics:

Fellowship

#### Discounted Skills:

Awareness

Charm

Command

Deceive

Security

Stealth

### CAREER PATH: Heretek

#### Free Specialties/Talents:

Common Lore (Adeptus Mechanicus, Tech)

Forbidden Lore (Archeotech, The Warp)

Scholastic Lore (Astromancy OR Chymistry)

Language (Techna Lingua)

Mechadendrite use \[\]

Mechanicus Implants \[\]

#### Discounted Characteristics:

Intelligence

#### Discounted Skills:

Tech-Use

Scholastic Lore

Forbidden Lore

Investigation

Trade

Security

### CAREER PATH: Renegade

#### Free Specialties/Talents:

Common Lore (War)

Scholastic Lore (Tactica Imperalis)

Pilot (any)

Adroit \[Choose one Characteristic at Character Creation. That
Characteristic becomes a Discounted Characteristic\]

#### Discounted Characteristics:

\-

#### Discounted Skills:

Athletics

Awareness

Medicae

Tech-Use

Stealth

Survival

Ballistic Skill

Weapon Skill

### CAREER PATH: Psyker

#### Free Specialties/Talents:

Forbidden Lore (Psykers, Daemons, The Warp)

Jaded \[Impervious to mundane horrors\]

Psyniscience \[Can detect Psychic activity\]

Chaos Psyker \[Can manifest Psychic Powers\]

#### Discounted Characteristics:

Willpower

#### Discounted Skills:

Awareness

Intimidate

Investigation

Deceive

Forbidden Lore

Scholastic Lore

## CORRUPTION AND INFAMY

Heretic characters begin with 0 Corruption and replace their Fate stat
with an Infamy stat. A Heretic's Corruption of 0 is the same as a
loyalist character's Corruption of 10. If an Imperial character gains 10
Corruption, the player and GM may wish to convert that character to a
Heretic character by resetting to 0 Corruption and gaining an Infamy
track (this will reset to the default Fate point value, regardless of
how upgraded it was before: The Emperor's Light no longer blesses them).

Instead of just the usual +3 to rolls or +2 to Defense that Fate points
grant, Infamy points grant differing bonuses depending on your
Corruption level as follows:

+-----------------------------------+-----------------------------------+
| Corruption Level                  | Infamous Bonus                    |
+===================================+===================================+
| 0-2                               | -   Add +3 to a Dice Pool for one |
|                                   |     roll                          |
|                                   |                                   |
|                                   | -   Add +2 to Defense for one     |
|                                   |     turn                          |
+-----------------------------------+-----------------------------------+
| 3-6                               | -   Heal 1d5 Wounds               |
|                                   |                                   |
|                                   | -   Re-roll a test once           |
|                                   |                                   |
|                                   | -   Add one success to an already |
|                                   |     successful test               |
+-----------------------------------+-----------------------------------+
| 7-10                              | -   Heal 1d10 Wounds              |
|                                   |                                   |
|                                   | -   Gain 10 initiative for one    |
|                                   |     turn                          |
+-----------------------------------+-----------------------------------+

In addition, the character's alignment will give a Bonus and a Drawback
to Infamy use (Unaligned characters gain neither):

  -----------------------------------------------------------------------
  Chaos God               Infamy Bonus            Infamy Drawback
  ----------------------- ----------------------- -----------------------
  Nurgle                  When rolling to heal    May not spend Infamy to
                          wounds using Infamy,    re-roll tests
                          automatically heal the  
                          highest possible number 

  Khorne                  May spend an Infamy     When rolling to heal
                          point to automatically  wounds using Infamy,
                          pass an attack roll     reduce the result by 2
                          with one success        to a minimum of 1

  Slaanesh                May spend an Infamy     May not spend Infamy to
                          point to ignore all the add a success to an
                          effects of an attack,   already successful test
                          including damage        

  Tzeentch                When spending an Infamy May not spend Infamy to
                          point to add a success  add +3 to a dice pool
                          to an already           
                          successful test, add 2  
                          instead                 
  -----------------------------------------------------------------------

# DRUKHARI CHARACTERS

Drukhari characters do not gain Home World or Role bonuses, but instead
all hail from Commoragh. They all gain the following starting Talents,
then choose a Career Path and a Vile Pleasure. Starting size is 6.

#### Starting Talents:

Language (Aeldari) \[Can speak the Eldar tongue\]

Language (Drukhari) \[Can speak the Drukhari tongue\]

Heightened Senses \[All five senses are superhuman\]

Darksight \[Can see in the dark\]

Hard Target \[+1 to defense\]

Paranoia \[+1 to dice pool when detecting hidden threats\]

Catfall \[Treat distance fallen as if it was a number of metres fewer,
equal to dots in agility\]

Unnatural Agility \[Rolls using Agility pass on 6+ rather than 8+\]

Non-Imperial \[-1 to dice pool for rolls regarding Imperial Lore or
dealing with unfamiliar Imperial Citizens\]

Jaded \[Impervious to mundane horrors\]

Dark Soul \[50% chance of not accruing a Corruption point\]

Power Through Pain \[Every time they inflict or experience pain they
gain a Pain Token. Eight Pain Tokens regain a Fate point\]

Trueborn (Optional: replaces a standard merit) \[+1 dice pool for all
rolls in which Trueborn status is a boon\]

#### Free Specialties:

Common Lore (War)

Common Lore (Kabals)

Forbidden Lore (Dark Eldar)

Tech-Use (Chems)

#### Discounted Skills:

Awareness

Acrobatics

Stealth

Intimidate

## CAREER PATHS

### CAREER PATH: KABALITE

#### Free Specialties:

Ballistic Skill (any Drukhari ranged weapon)

#### Discounted Skills:

Ballistic Skill

### CAREER PATH: WYCH

#### Free Specialties:

Weapon Skill (any Drukhari Wych melee weapon)

#### Discounted Skills:

Weapon Skill

### CAREER PATH: SKYTERROR

#### Free Specialties:

Pilot (Skyboard OR Reaver Jetbike OR Drukhari aircraft)

#### Discounted Skills:

Weapon Skill

### CAREER PATH: FLESHCRAFTER

#### Free Specialties:

Trade (Chymist OR Chirurgeon)

#### Discounted Skills:

Trade

### CAREER PATH: INCUBUS INITIATE\*

Must have Weapon Skill 5 and 5 Willpower. Cannot usually be taken at
Character Creation.

#### Free Specialties:

Weapon Skill (Klaive and Demiklaive)

#### Discounted Skills:

Weapon Skill

## VILE PLEASURES

### VILE PLEASURE: ARTFUL TORMENT

When dealing damage to a living creature that is stunned or restrained,
gain an additional pain token

### VILE PLEASURE: BOUNTIFUL SLAUGHTER

When killing or causing significant blood loss, gain an additional pain
token

### VILE PLEASURE: CRUEL DEMISE

When causing suffering using ranged weaponry, gain an additional pain
token if the target is within 20 x your character's perception in metres

### VILE PLEASURE: LINGERING DREAD

When inflicting fear (e.g. intimidate) or stunning, gain an additional
pain token

### VILE PLEASURE: SADISTIC JOY

When an ally suffers, gain an additional pain token

# ARMORY

New Special rules:

Astartes \[May re-roll 1s for attack rolls, weapon itself cannot be used
by unless character is an Astartes\]

Maximal \[May double the ammo spent in a single attack to double the
damage\]

Overheats \[When attacking, separately roll a 1d10. On a 1, the user
takes the full damage from the weapon in addition to the result of the
roll\]

Power \[When parrying a weapon that is not a Power, Force, Warp, or
Natural weapon, roll 1d10. On 4+ the opposing weapon is destroyed\]

## Ranged Weapons

### Bolt Weapons

  -----------------------------------------------------------------------------------------------------
  Name      Class    Damage   Ranges   Clip   Initiative   Strength   Size   Availability   Special
  --------- -------- -------- -------- ------ ------------ ---------- ------ -------------- -----------
  Bolt      pistol   5A       30, 60,  8      -2           3          1      4              AP 4
  Pistol                      120                                                           

  Boltgun   basic    5A       50, 100, 24     -3           3          3      4              AP 4
                              200                                                           

  Heavy     heavy    6A       150,     60     -4           4          5      5              Autofire
  Bolter                      300, 600                                                      (full auto
                                                                                            only), AP 4

  Storm     basic    5A       40, 90,  60     -3           3          3      5              Autofire,
  Bolter                      180                                                           AP 4
  -----------------------------------------------------------------------------------------------------

### Flame Weapons

  ------------------------------------------------------------------------------------------------------
  Name      Class    Damage   Ranges   Clip   Initiative   Strength   Size   Availability   Special
  --------- -------- -------- -------- ------ ------------ ---------- ------ -------------- ------------
  Hand      pistol   4A       5, 10,   2      -2           2          2      4              Incendiary
  Flamer                      20                                                            

  Flamer    basic    4A       10, 20,  6      -4           3          3      4              Incendiary
                              40                                                            

  Heavy     heavy    5A       20, 30,  4      -5           4          5      5              Incendiary
  Flamer                      50                                                            
  ------------------------------------------------------------------------------------------------------

### Las Weapons

  --------------------------------------------------------------------------------------------------------
  Name        Class    Damage   Ranges     Clip   Initiative   Strength   Size   Availability   Special
  ----------- -------- -------- ---------- ------ ------------ ---------- ------ -------------- ----------
  Laspistol   pistol   1        20,40,80   30     0            2          1      2              Maximal

  Lasgun      basic    2        150, 300,  60     -3           3          3      3              Maximal,
                                600                                                             Autofire

  Laslock     basic    2        150, 300,  1      -3           3          3      2              \-
                                600                                                             

  Long Las    basic    2        200, 400,  40     -4           3          3      4              Maximal,
                                800                                                             AP 1

  Hot-shot    pistol   2        50, 100,   40     -2           2          1      5              AP 2
  Laspistol                     200                                                             

  Hot-shot    basic    4        20, 40, 80 30     -3           3          3      5              AP 2
  Lasgun                                                                                        
  --------------------------------------------------------------------------------------------------------

### Launcher Weapons

  ---------------------------------------------------------------------------------------------------------
  Name       Class   Damage   Ranges      Clip   Initiative   Strength   Size   Availability   Special
  ---------- ------- -------- ----------- ------ ------------ ---------- ------ -------------- ------------
  Grenade    basic   \*       40,80,160   6      -3           3          3      5              \*see
  Launcher                                                                                     Grenades and
                                                                                               Explosives

  Missile    heavy   \*       200, 400,   1      -5           4          5      5              \* see
  Launcher                    800                                                              Grenades and
                                                                                               Explosives
  ---------------------------------------------------------------------------------------------------------

### Low-Tech Weapons

  -----------------------------------------------------------------------------------------------------------
  Name       Class    Damage   Ranges      Clip   Initiative   Strength   Size   Availability   Special
  ---------- -------- -------- ----------- ------ ------------ ---------- ------ -------------- -------------
  Bolas      thrown   1        x3,x6,x12   1      -2           2          2      \-             Range based
                                                                                                on
                                                                                                Str+Agi+Ath

  Bow        basic    2        40, 80, 160 1      -3           2          3      2              \-

  Crossbow   basic    2        40, 80, 160 1      -5           3          2      3              \-
  -----------------------------------------------------------------------------------------------------------

### Melta Weapons

  ------------------------------------------------------------------------------------------------------
  Name       Class    Damage   Ranges     Clip   Initiative   Strength   Size   Availability   Special
  ---------- -------- -------- ---------- ------ ------------ ---------- ------ -------------- ---------
  Inferno    pistol   10A      10,20,40   12     -2           2          2      5              AP 10
  Pistol                                                                                       

  Meltagun   basic    10A      20, 40, 80 12     -4           3          3      5              AP 10
  ------------------------------------------------------------------------------------------------------

### Plasma Weapons

  -----------------------------------------------------------------------------------------------------
  Name      Class    Damage   Ranges   Clip   Initiative   Strength   Size   Availability   Special
  --------- -------- -------- -------- ------ ------------ ---------- ------ -------------- -----------
  Plasma    pistol   7A       30, 60,  10     -2           2          2      5              Maximal,
  Pistol                      120                                                           Overheats

  Plasma    basic    7A       150,     20     -5           3          3      5              Maximal,
  Gun                         300, 600                                                      Overheats
  -----------------------------------------------------------------------------------------------------

### Solid Projectile Weapons

  ---------------------------------------------------------------------------------------------------------
  Name         Class    Damage   Ranges     Clip   Initiative   Strength   Size   Availability   Special
  ------------ -------- -------- ---------- ------ ------------ ---------- ------ -------------- ----------
  Autopistol   pistol   1        20,40,80   18     0            2          1      3              Autofire

  Autogun      basic    2        50, 100,   30     -3           3          2      3              Autofire
                                 200                                                             

  Autocannon   heavy    3        150, 300,  24     -3           3          3      3              Autofire
                                 600                                                             (full auto
                                                                                                 only), AP
                                                                                                 3

  Hand Cannon  pistol   2        30, 60,    2      -2           3          1      2              AP 1
                                 120                                                             

  Heavy        heavy    2        50, 100,   80     -3           3          3      3              Autofire
  Stubber                        200                                                             

  Shotgun      basic    2        20, 40, 80 8      -4           3          2      2              9-Again

  Shotgun      basic    2        20, 40, 80 18     -4           3          2      2              9-Again
  (combat)                                                                                       

  Sniper Rifle basic    5        200, 400,  6      -5           3          4      5              AP 3
                                 800                                                             

  Stub         pistol   2        30, 60,    9      -2           3          3      3              \-
  Automatic                      120                                                             

  Stub         pistol   1        20, 40, 80 6      0            2          1      2              \-
  Revolver                                                                                       
  ---------------------------------------------------------------------------------------------------------

### Xenos Weapons

### Chaos Weapons

## Melee Weapons

### Chain Weapons

### Force Weapons

### Low-Tech Weapons

### Power Weapons

### Shock Weapons

### Xenos Weapons

### Chaos Weapons

## Grenades and Explosives

  -----------------------------------------------------------------------------------------------
  Name           Damage   Blast   Force   Strength   Initiative   Availability   Special
                          Area                                                   
  -------------- -------- ------- ------- ---------- ------------ -------------- ----------------
  Blind Grenade  0        10      \-      2          0            5              Concealment,
                                                                                 Stun

  Choke Grenade  0        10      \-      2          0            5              Concealment,
                                                                                 Sedative

  Frag Grenade   2        10      3       2          0            2              Knockdown, Stun

  Hallucinogen   0        10      \-      2          0            5              Concealment,
  Granade                                                                        Hallucinogenic

  Haywire        0        10      \-      2          0            4              EMP
  Grenade                                                                        

  Krak Grenade   3        5       4       2          -1           3              Knockdown, Stun

  Flash Grenade  0        5       \-      2          0            2              Stun

  Smoke Grenade  0        10      \-      2          0            5              Concealment

  Stun Grenade   0        5       2       2          0            3              Knockdown, Stun

  Web Grenade    0        10      2       2          0            4              Snare

  Fire Bomb      1        3       2       2          -2           2              Incendiary

  Melta Bomb     10A      5       4       2          -3           5              AP 8, Incendiary

  Frag Missile   6        10      3       \-         \-           2              AP 2

  Krak Missile   8        5       4       \-         \-           3              AP 8
  -----------------------------------------------------------------------------------------------

# PSYCHIC POWERS

## Biomancy Discipline

Enfeeble

Endurance

Haemorrhage

Invigourate

Iron Arm

Life Leech

Shape Flesh

Smith

Warp Speed

## Divination

Foreboding

Forewarning

Misfortune

Perfect Timing

Precognition

Prescience

Scrier's Gaze

Warp Perception

Winding Fate

## Pyromancy

Cauterise

Flame Breath

Fiery Form

Fire Shield

Inferno

Manipulate Flame

Molten Beam

Spontaneous Combustion

Sunburst

## Telekinesis

Assail

Crush

Gate of Infinity

Objuration Mechanicum

Shockwave

Telekine Dome

Tekekine Shield

Tekekinetic Control

Vortex of Doom

## Telepathy

Dominate

Erasure

Hallucination

Invisibility

Mental Fortitude

Psychic Shriek

Puppet Master

Telepathic Link

Terrify

## Chaos Unaligned

Abhorrent Ward

Doombolt

Foul Cage

Gift of Chaos

Hatestorm

Host of Fiends

Warptime

Wind of Chaos

## Nurgle

Choir of Poxes

Inviolable Flesh

Leper's Curse

Nurgle's Rot

Field of Pestilence

Putrefying Embrace

Rain of Foulness

## Slaanesh

Acquiescence

Ecstatic Oblivion

Hellshriek

Lash of Submission

Soul's Secrets Unleashed

Symphony of Pain

## Tzeentch Powers

Bolt of Change

Boon of Tzeentch

Flicker

Gholam Curse

Mantle of Lies

Mindscourge

Protean Form

Psyphon

Vile Revelation

## Exalted Powers

Blasphemy Made Flesh

Hellish Blast

Maelstrom of Rage

Primordial Annihilation

Shattertime

Sunder the Veil
